version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fren_relay_postgres
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: